### PR TITLE
Initial work for OpenHab 2 support

### PR DESCRIPTION
**Pull request by bbustin**
OpenHab 2 removed Websockets and instead opted for Server Side Events (SSE). This pull request has work that I did to try to make OpenHAB-HomeKit-Bridge work with OpenHab 2.

Major changes:
- refactored some of the methods for the items into a common class
- created an SSE listener to which items can register their callbacks. The SSE listener gets all OpenHab events, so if an event corresponds to a registered item, then the value is passed to that item's callback.
- using a newer version of hap-nodejs and node-persist

This code is not well-tested. Areas of concern/risks with this new code:
- Have not tested whether new code still works with OpenHab 1. The goal was to keep current behavior intact unless "--version 2" is passed.
- Temperature updates have the wrong numbers. Messages logged to the console; however, appear to have the correct number.
- Have only tested switch items and temperature items, yet changes affected all types.
- Appear to have some difficulty adding Accessory to HomeKit app on my phone (using Eve app). Was not having this difficulty in commit e163c84, but have yet to identify any changes since then which I think would lead to this behavior.
- Javascript is not one of the languages I use regularly, so the code might not be as elegant as it should be.

Hope this code helps. If you feel this code is worthy of pulling, feel free to add any comments when reviewing it so I can correct them first.

Happy holidays,
Brian

### CODE REVIEW

**Comment by htreu** [comment]
Thanks a lot for the PR. I will need some time to work through the code. Stay tuned.

**Comment by bbustin** [comment]
My pleasure. Hope there is something useable for you here. 

I have since resolved the temperature displaying an incorrect value issue. It was caused by HomeKit using Celsius internally and my sensors using Fahrenheit. I defaulted the code to assume Celsius, but if the display format ends in F, then do a conversion to Celsius. 

I also added the beginnings of a thermostat accessory that combines multiple OpenHab items. It currently only works with OpenHab2 and I feel the way I implemented it leaves a lot to be desired. I was trying to find a way where OpenHab HomeKit Bridge could automatically figure out the items to use for thermostat accessory and their roles. I documented how to set up items and sitemap for this in the readme.

*This code is still not tested with OpenHab 1. I plan to merge the latest changes in master into this pull request at some point and resolve any conflicts when I get a chance to work on this some more.*

**Comment by bbustin** [comment]
Rebased on the latest code... Not sure it all went through correctly. I was also unable to use AccessoryProvider and had to go back to using the old ItemProvider for now as that is where I put some logic about wht type of units or how to group multiple items into one accessory. There is surely a better way than I have done it, but I will have to leave that as an excercise for another day...

**Comment by htreu** [comment]
I did some major improvements regarding stability & test coverage.
When I checked your branch I saw quite a few different things which you implemented. Here is my suggestion: Please split the stuff into different branches. Then we can begin with basic OH2 support and work our way through the rest of the features/improvements.
What do you think?

**Comment by bbustin** [comment]
I think that is a good idea. Unfortunately, I have had a bunch of circumstances that have been keeping me from working on this.

**Pull request closed without merging**
